#ifndef TUNNELCOREOBFUSCATION_H
#define TUNNELCOREOBFUSCATION_H

#include <QByteArray>
#include <QRandomGenerator>
#include <QString>
#include <QStringList>

namespace TunnelCoreObfuscation
{

struct PacketSet
{
    QString profile;
    QString sourceDomain;
    QStringList packets;
};

struct DnsProfile
{
    const char *key;
    const char *sourceDomain;
    QStringList domains;
};

inline QString hexU16(int value)
{
    const quint16 v = quint16(value & 0xffff);
    QByteArray bytes;
    bytes.append(char((v >> 8) & 0xff));
    bytes.append(char(v & 0xff));
    return QString::fromLatin1(bytes.toHex());
}

inline QString dnsNameHex(const QString &domain)
{
    QByteArray encoded;
    const auto labels = domain.toUtf8().split('.');
    for (const auto &label : labels) {
        if (label.isEmpty() || label.size() > 63)
            return {};
        encoded.append(char(label.size()));
        encoded.append(label);
    }
    encoded.append(char(0));
    return QString::fromLatin1(encoded.toHex());
}

inline QString dnsQueryExpression(const QString &domain, bool ipv6, int paddingBytes)
{
    const auto qname = dnsNameHex(domain);
    if (qname.isEmpty())
        return {};

    // DNS query with EDNS0 padding. The transaction id and padding bytes are
    // generated by AmneziaWG at packet-send time; the padding length and query
    // type are additionally varied for every TunnelCore connection.
    const auto queryType = ipv6 ? QStringLiteral("001c") : QStringLiteral("0001");
    const auto rdLength = hexU16(4 + paddingBytes);
    const auto paddingLength = hexU16(paddingBytes);

    return QStringLiteral(
        "<r 2><b 0x01000001000000000001%1%2000100002904d000000000%3000c%4><r %5>")
        .arg(qname, queryType, rdLength, paddingLength)
        .arg(paddingBytes);
}

inline PacketSet generate(const QString &requestedProfile)
{
    const QList<DnsProfile> profiles {
        {
            "mail_dns",
            "mail.ru",
            {
                QStringLiteral("mail.ru"),
                QStringLiteral("cloud.mail.ru"),
                QStringLiteral("id.mail.ru"),
                QStringLiteral("auth.mail.ru"),
                QStringLiteral("api.mail.ru"),
            },
        },
        {
            "yandex_dns",
            "yandex.ru",
            {
                QStringLiteral("yandex.ru"),
                QStringLiteral("mail.yandex.ru"),
                QStringLiteral("passport.yandex.ru"),
                QStringLiteral("disk.yandex.ru"),
                QStringLiteral("api.yandex.ru"),
            },
        },
        {
            "vk_dns",
            "vk.com",
            {
                QStringLiteral("vk.com"),
                QStringLiteral("api.vk.com"),
                QStringLiteral("id.vk.com"),
                QStringLiteral("static.vk.com"),
                QStringLiteral("oauth.vk.com"),
            },
        },
    };

    auto requested = requestedProfile.trimmed().toLower();
    int profileIndex = -1;
    if (!requested.isEmpty() && requested != QStringLiteral("auto")) {
        for (int i = 0; i < profiles.size(); ++i) {
            if (requested == QLatin1String(profiles.at(i).key)) {
                profileIndex = i;
                break;
            }
        }
    }

    auto *rng = QRandomGenerator::system();
    if (profileIndex < 0)
        profileIndex = int(rng->bounded(quint32(profiles.size())));

    const auto &profile = profiles.at(profileIndex);
    const int domainOffset = int(rng->bounded(quint32(profile.domains.size())));

    PacketSet result;
    result.profile = QLatin1String(profile.key);
    result.sourceDomain = QLatin1String(profile.sourceDomain);
    result.packets.reserve(5);

    for (int i = 0; i < 5; ++i) {
        const auto &domain = profile.domains.at((domainOffset + i) % profile.domains.size());
        const bool ipv6 = rng->bounded(2u) == 1u;

        // Keep the complete CPS packet comfortably below a typical VPN MTU.
        // Different ranges also avoid five identically-sized prefix packets.
        const int minPadding = 24 + i * 7;
        const int maxPaddingExclusive = 72 + i * 11;
        const int paddingBytes = minPadding
                                 + int(rng->bounded(quint32(maxPaddingExclusive - minPadding)));

        result.packets.append(dnsQueryExpression(domain, ipv6, paddingBytes));
    }

    return result;
}

} // namespace TunnelCoreObfuscation

#endif // TUNNELCOREOBFUSCATION_H
